FROM continuumio/miniconda3:latest

RUN apt-get update && apt-get -y --no-install-recommends install \
    gosu \
    build-essential

RUN conda config --add channels conda-forge && \
    conda config --set channel_priority true && \
    conda update --all && \
    conda install -c conda-forge satpy \
    pyresample \
    pykdtree \
    trollsift \
    trollimage \
    pycoast \
    pyorbital \
    rasterio \
    gdal \
    h5py \
    ipython \
    pyinotify \
    pyzmq \
    h5netcdf \
    netifaces \
    meld3 \
    scp \
    paramiko \
    dpath \
    toolz \
    configobj && \
    conda remove --force satpy pyresample trollimage pycoast pyorbital pykdtree trollsift && \
    conda clean -a -y
ADD requirements_dev.txt /tmp/
RUN pip install -r /tmp/requirements_dev.txt && \
    rm -r /tmp/requirements_dev.txt
    #python -c 'from pyspectral.utils import download_luts; \
    #  from pyspectral.utils import logging_on; import logging; \
    #  logging_on(logging.DEBUG); download_luts()' && \
    #python -c 'from pyspectral.utils import download_rsr; \
    #  from pyspectral.utils import logging_on; import logging; \
    #  logging_on(logging.DEBUG); download_rsr()' && \
    #mkdir -p /home/user/.local/share && \
    #mv /root/.local/share/pyspectral /home/user/.local/share/
RUN apt-get -y remove build-essential

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["supervisord", "-c", "/mnt/config/supervisord.conf"]
